import type {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage,
} from "next";
import Head from "next/head";
import Image from "next/image";
import Router from "next/router";
import styles from "../styles/Home.module.css";

const Home: NextPage = ({
  name,
}: InferGetServerSidePropsType<GetServerSideProps>) => {
  console.log("CLIENT", name);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create {name} Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className="text-red-700 font-bold text-lg md:text-7xl bg-blue-400 dark:bg-slate-900">
          Welcome to{" "}
          <a href="https://nextjs.org">
            <span className="text-green-700">{name}</span> SITE
          </a>
        </h1>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const name = context.params?.name;
  return { props: { name: name } };
};

export default Home;
